name: Build, Test, & Publish '@schemavaults/theme' Package

on:
  push:
    branches:
      - main

permissions:
  packages: write

env:
  BUN_VERSION: 1.2.22

jobs:
  build-test-and-publish:
    name: "Build, test, & publish package"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ env.BUN_VERSION }}
      - name: Install dependencies with Bun
        run: bun install
      - name: Build package with Bun
        run: bun run build
      - name: Run package unit tests
        run: bun run test
      - name: Configure .npmrc to publish to GitHub NPM registry
        run: cp .npmrc.github .npmrc
      - name: Publish package to GitHub NPM registry
        run: bun publish --registry=https://npm.pkg.github.com
        env:
          SCHEMAVAULTS_GITHUB_PACKAGE_REGISTRY_USER: ${{ github.actor }}
          SCHEMAVAULTS_GITHUB_PACKAGE_REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Delete .npmrc for GitHub NPM registry
        run: rm -rf .npmrc
      - name: Configure .npmrc to publish to NPMJS registry
        run: cp .npmrc.github .npmrc
      - name: Print user for publishing to NPM
        run: echo "Attempting to publish package as user $NPM_PACKAGE_PUBLISH_USER"
      - name: Publish package to NPMJS registry
        run: bun publish --registry=https://registry.npmjs.org
        env:
          NPM_PACKAGE_PUBLISH_USER: ${{ env.NPM_PACKAGE_PUBLISH_USER }}
          NPM_PACKAGE_PUBLISH_TOKEN: ${{ secrets.NPM_PACKAGE_PUBLISH_TOKEN }}
      - name: Delete .npmrc for NPMJS registry
        run: rm -rf .npmrc
